### ISSUE TITLE
Resource packs for random entity textures and health based textures broken.

### ISSUE THREAD

**Issue by keatit71** [Traben-0/EmissiveMod#10]
I'm not sure why the mob textures aren't working but everytime it hasn't been a missing file texture its just been invisible and any textures on the mob are glitched.

[BetterVanillaAnimals_v1.8.7.zip](https://github.com/Traben-0/EmissiveMod/files/7979685/BetterVanillaAnimals_v1.8.7.zip)
[realistic monster-damage-1-18.zip](https://github.com/Traben-0/EmissiveMod/files/7979689/realistic.monster-damage-1-18.zip)

[latest.log](https://github.com/Traben-0/EmissiveMod/files/7979691/latest.log)
[modlist.txt](https://github.com/Traben-0/EmissiveMod/files/7979697/modlist.txt)
[resourcepacklist.txt](https://github.com/Traben-0/EmissiveMod/files/7979710/resourcepacklist.txt)

**Comment by Traben-0** [comment]
This seems to be fixed for V2.1.3 that'll be out soon, I can no longer reproduce any of these.

Heads up those packs don't seem to be working fully with CEM so the textures don't wrap on the vanilla models well, but they do randomise accoring to the rules in the properties files :)
