### ISSUE TITLE
Incorrect enumeration of random textures

### ISSUE THREAD

**Issue by coornio** [Traben-0/EmissiveMod#13]
This was debugged using the John Smith Legacy (v6) for 1.18.1 resource pack.

I noticed that there was a greatly reduced mob variety. It was fairly easy to test with the creeper textures due to their distinctive designs and their modest amount of skins in this pack.  It uses the `assets/minecraft/optifine/mob` path for random textures, and it counts them from index 2 and up. Default textures for entities are present under `assets/minecraft/textures`.

This is what it looks like by default with this mod enabled: 
![2022-02-13_23 12 26](https://user-images.githubusercontent.com/11655762/153775430-a87217de-1e72-4b48-915d-0609c9ef86a1.png)

The skins depicted here are ordered from right to left. Rightmost is the default skin (1), and leftmost is skin 5. However, the skins shown with the mod, from right to left, are actually 3, 4, 3, 3, 1. Something is very wrong.

I tried as an experiment to take the default skin and placed it in the respective folders under `optifine/mob` where the extra skins were, then added `1` as a suffix to the name of each skin. Rebooted the game, and this is the result:
![2022-02-13_20 38 18](https://user-images.githubusercontent.com/11655762/153775791-4fbb8ad0-c8d2-49f1-8cc4-d12458b52baf.png)

NOW the skins are showing properly. Something is wrong with how the mod is counting the skins, possibly some weird off-by-one situation in the calculations when it checks for an index starting from 2 rather than 1. Below I will list all the creeper skins for reference so you can confirm their order as well:

![creeper1](https://user-images.githubusercontent.com/11655762/153775850-826621e1-424f-4ade-9337-24109e580df0.png)
![creeper2](https://user-images.githubusercontent.com/11655762/153775851-2361a9c4-b3ed-4691-9b28-de8f1a6cac02.png)
![creeper3](https://user-images.githubusercontent.com/11655762/153775853-bf5b15a6-750e-4e2d-9bc7-53427d3e1d74.png)
![creeper4](https://user-images.githubusercontent.com/11655762/153775854-a6bba159-3e44-48d5-a083-1711d9a0be9d.png)
![creeper5](https://user-images.githubusercontent.com/11655762/153775855-ccc171ff-c9f8-440c-9146-25f693b0e973.png)

Please have a look into this! I'd like to continue using this mod without having to modify my resource pack to work! :)

**Comment by Traben-0** [comment]
you were dead on :) it was not handling counting from 2 correctly, it's fixed as of V2.1.4 which should release tonight

**Comment by coornio** [comment]
Cheers! <3
