### ISSUE TITLE
This is not right

### ISSUE THREAD

**Issue by CormacZ** [Traben-0/EmissiveMod#14]
![image](https://user-images.githubusercontent.com/71203678/153840269-15f33e0e-d58a-4cf8-99b9-e6e1251646db.png)
https://www.planetminecraft.com/texture-pack/glamrock-freddy-fazbear-optifine-1-18/

**Comment by Desynq** [comment]
This mod doesn't support custom entity models afaik, only random textures and emissive textures.

You could try your luck with this mod, although it may not hold 100% true parity with OptiFine's CEM format:
https://www.curseforge.com/minecraft/mc-mods/custom-entity-models-cem
