### ISSUE TITLE
1.17.1

### ISSUE THREAD

**Issue by CreeperCoder63** [Traben-0/EmissiveMod#15]
Hello,
Wondering if there already is a 1.17.1 version of this mod somewhere. I really would like to use it in my personal mod pack, although the curseforge page does not have 1.17.1 listed. Is it possible to backport the mod?

**Comment by Traben-0** [comment]
i'll give it a go

**Comment by Traben-0** [comment]
its up on curseforge and modrinth

**Comment by CreeperCoder63** [comment]
> its up on curseforge and modrinth

thx
