### ISSUE TITLE
[Suggestion] Entity Name Based Textures

### ISSUE THREAD

**Issue by CodeF53** [Traben-0/EmissiveMod#16]
Not sure if this is out of scope for the mod or not, but one of my favorite features from optifine stuff is being able to customize an entity based on a given name.

**Comment by Traben-0** [comment]
this is a feature of the mod already, It actually does it exactly how optifine does so you can use an optifine texture pack

**Comment by CodeF53** [comment]
You should probably list that on curseforge and modrinth then.

**Comment by Traben-0** [comment]
it does, the mod page is quite wordy, I may have to write a summary
