### ISSUE TITLE
Does not work on any server.

### ISSUE THREAD

**Issue by ProFFesor117** [Traben-0/EmissiveMod#18]
Hello.
I use this mod and [Visual-Impair](https://www.planetminecraft.com/texture-pack/visual-impair-1-2-opti-fine-required/) resource pack.
In a singleplayer, everything works fine.
But in the multiplayer it does not work.
Sorry for my English.

**Comment by Traben-0** [comment]
I know what's causing this looking into it now, my singleplayer implimentation reduced lag considerably, but I have some ideas for making this work

**Comment by Traben-0** [comment]
try Version 2.3.2, uploaded now on curseforge, should fix things for that pack while on servers, if its not fast enough you can increase the texture update frequency in the config/modmenu settings
