### ISSUE TITLE
Player Skin Features: emissive + blinking bug

### ISSUE THREAD

**Issue by Tectato** [Traben-0/EmissiveMod#21]
Emissive pixels in the face don't seem to update during the blinking animation
![emissiveEyesBug](https://user-images.githubusercontent.com/70598501/156775351-a0073c68-0e86-4fb3-aa4b-51c1fc9ea0d5.gif)

Skin used (All pixels with emission colour selected):
![grafik](https://user-images.githubusercontent.com/70598501/156775525-8540ca5c-b3f1-4d14-8169-e4ffcf5f6d66.png)

**Comment by Traben-0** [comment]
small oversight as I added blinking after I added emissive support, should have a fix up tomorrow night, I actually just fixed this for non-player mobs behind the scenes just now so that will be fixed too

**Comment by Tectato** [comment]
Jolly good, amazing work on the mod so far!

**Comment by Traben-0** [comment]
V2.3.3 uploading now with a fix as well as first person hand skin features rendering
