### ISSUE TITLE
ETF conficts with IRIS

### ISSUE THREAD

**Issue by cili96** [Traben-0/EmissiveMod#22]
[latest.log](https://github.com/Traben-0/EmissiveMod/files/8254891/latest.log)
I guess the confict is due to the transparent capes and iris not recognising them.

**Comment by ENTPRESTIGIOUS** [comment]
I've just updated to the latest version and it blames Iris, crashing my game in the process. The older version works fine.

**Comment by Poopooracoocoo** [comment]
I saw crashes even without Iris.

**Comment by ENTPRESTIGIOUS** [comment]
> I saw crashes even without Iris.

I disabled Iris and yeah it said no mods are affecting this error. When I looked into the crash log, it says emissive or something.

**Comment by Poopooracoocoo** [comment]
(That's Not Enough Crashes telling you that it thinks Iris is to blame by the way.)

**Comment by ENTPRESTIGIOUS** [comment]
> (That's Not Enough Crashes telling you that it thinks Iris is to blame by the way.)

yep LUL

**Comment by Traben-0** [comment]
looking into this now 2.4.5 should work in the meantime

**Comment by Traben-0** [comment]
[entity-texture-features-1.18.x-iris-fix-try2.zip](https://github.com/Traben-0/EmissiveMod/files/8259649/entity-texture-features-1.18.x-iris-fix-try2.zip)
please try this fix as i cannot reproduce the error myself

**Comment by Poopooracoocoo** [comment]
When I open worlds with Fabulously Optimized modpack 3.3.0 beta 2 but with Entity Texture Features updated to 2.5.2 with GDLauncher, it crashes. I had also tried the same modpack without Iris and saw it crash again. 

This no longer occurs with the fix above.

**Comment by ENTPRESTIGIOUS** [comment]
> When I open worlds with Fabulously Optimized modpack 3.3.0 beta 2 but with Entity Texture Features updated to 2.5.2 with GDLauncher, it crashes.
> 
> This no longer occurs with the fix above.

That's weird because the latest version only causes problems for me and I'm using Sildur's Enhanced Vanilla Jan 1, 2022 build with Iris.

**Comment by ENTPRESTIGIOUS** [comment]
Also isn't Entity Texture Features supposed to replicate Optifine's Emissive Texture setting? I've read from LambDAurora or somebody's github website on Optifine alternatives. Since I had a Visible Ore texture pack, I wanted to use this to produce the illumination of the textures since the pack contains a ctm folder with .properties files.

**Comment by Traben-0** [comment]
this does optifine emissives but only foer entities so far, emissive blocks is a hole nother ball park i've started looking into and is very ahrd to make work with sodium

**Comment by Traben-0** [comment]
I have posted V2.5.3 with the fix
