### ISSUE TITLE
1 pixel blinking crash the game

### ISSUE THREAD

**Issue by TomyGamy** [Traben-0/EmissiveMod#24]
I'm using the mod to aply bliking to my skins, but at the blinking, it crash :

`The game crashed whilst rendering entity in world
Error: java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because the return value of "java.util.HashMap.get(Object)" is null
Code de sortie : -1`

I tried with full face blinking, and there's no problem.

Ther is one of them
![TomyGamy's skin - Copie](https://user-images.githubusercontent.com/95078425/158822407-0c2fcfb1-5c3f-4b83-942e-313539a2ebec.png)

The top left 8x8 zone is my signature.

**Comment by Traben-0** [comment]
fixed in beta 2.5.9
