### ISSUE TITLE
no working resource pack renaming

### ISSUE THREAD

**Issue by BMlight** [Traben-0/EmissiveMod#283]
![image](https://github.com/user-attachments/assets/8baaf843-7e33-4367-a3d0-f6e06029e71d)

This resource pack provides the ability to change the appearance of the original item by renaming it, but it is not working with ETF/EMF. The resource pack creator says report it to mod.

https://www.curseforge.com/minecraft/texture-packs/newdefaultplus/files/5388649 I use this. and mod list.

![image](https://github.com/user-attachments/assets/9d903615-1691-4af1-bf1d-e223a2d8be46)

![image](https://github.com/user-attachments/assets/b8b8cb7e-11f5-4c45-a0be-54ab24da943a)

**Comment by Traben-0** [comment]
emf and etf do not do this, only entity related features, you are looking for `CIT resewn`
