### ISSUE TITLE
[BUG] Minecraft Java 1.20.1 not starting

### ISSUE THREAD

**Issue by Bloodlex** [Traben-0/EmissiveMod#291]
*please make sure you are using the latest ETF version before submitting an issue, you might also find a dev build
fixing this issue already on my discord https://discord.com/invite/rURmwrzUcz in the #dev-blog channel*

**Describe the issue**

Minecraft Java doesn't start

**Crash log**

<html>Mod 'Entity Texture Features' (entity_texture_features) 6.1.3 requires any version between 1.20.5 (inclusive) and 1.21<br>(exclusive) of 'Minecraft' (minecraft), but only the wrong version is present: 1.21.1!</html>

I think it shouldn't be exclusive, but inclusive.

**Your setup: (please complete the following information):**

- Minecraft version: [e.g. 1.19.2] 1.20.1
- ModLoader: [e.g forge/fabric] fabric
- ETF Version [e.g. 4.0.1] 6.1.3
- Does the issue persist with only ETF installed? yes
- Have you checked the FAQ in the Readme, or Discord, to see if it is a known issue? yes

**Comment by Traben-0** [comment]
OK several things here, you keep saying 1.20.1 but your message says 1.21.1

By the sounds of your message you have downloaded the 1.20.6 version of etf you need the 1.21.1 version

Send a screenshot of the etf file in your mods folder if this is not the case
