### ISSUE TITLE
[Possible Issue] ETF Mod Flickering emissive textures when player model blinks?

### ISSUE THREAD

**Issue by BlueyBooey1278** [Traben-0/EmissiveMod#292]
Is anybody else experiencing this Issue for the Entity Features Mod, I noticed recently that If my Player Model has any of the blinking textures excluding the 1 Pixel tall one that my models emissive textures also turn off whenever my player model blinks? Im positive that Its a bug cause I don't remember It doing this before and It started happening for me just yesterday!
I don't have any mods that I know of that could Interfere with the ETF Mod, the only mod I have that affects the player model Is the Fresh Moves mod which Is just supposed to overhaul the player animations.

I have experienced this Issue so far In two Modpacks of mine on both Forge 1.20.1 & Fabric 1.21 and Im not sure how to fix It!

Screenshots of my Player Model normally: 
![2024-08-11_11 00 58](https://github.com/user-attachments/assets/dbe2412c-65c1-4668-ae6c-a420ddd731a5)
![2024-08-11_11 00 38](https://github.com/user-attachments/assets/2b6e4612-4215-45e1-8be3-12436930210e)

Screenshots of my Player Models emisive textures turning off: 
![2024-08-11_11 00 59](https://github.com/user-attachments/assets/8cd02fb9-fd43-4faa-9d85-823f829e8555

And before you ask no I didn't change any of the settings and I am wearing the ETF version of my Minecraft Skin, my shaders are also not the problem either I don't think cause they worked just fine all the times before.

- Minecraft version: [1.20.1 & 1.21]
- ModLoader: [forge & fabric]
- ETF Version [6.1.1 & 6.1.3]

**Comment by Traben-0** [comment]
I am aware of this

**Comment by BlueyBooey1278** [comment]
Real
