### ISSUE TITLE
Menu not working

### ISSUE THREAD

**Issue by Ashlockheart** [Traben-0/EmissiveMod#294]
Minecraft version 1.20.1
Forge version 47.3.0
ETF version 1.20.1-6.2.jar
EMF Version 1.20.1-2.2.jar

When I click on the ETF/EMF button under resource pack their is some visual issue that happens.
Resourcepack is Conquest
![Screenshot (52)](https://github.com/user-attachments/assets/9cd72fd2-d37f-41d0-89f0-20ecf2aa4a6a)

**Comment by Traben-0** [comment]
I'm aware of this but its good to have an issue for it

**Comment by TooterTutor** [comment]
I seem to also face the same issue on Fabric when opening the configs.

Minecraft Version: 1.20.1
Fabric Loader Version: 0.16.5
ETF Version: 6.2.7
EMF Version: 2.2.6
ESF Version: 0.4

**Comment by Traben-0** [comment]
i jsut released etf 6.2.8 with the fix
