### ISSUE TITLE
[BUG] 1.20.1 Only Log Error

### ISSUE THREAD

**Issue by Krimatoria** [Traben-0/EmissiveMod#295]
*please make sure you are using the latest ETF version before submitting an issue, you might also find a dev build
fixing this issue already on my discord https://discord.com/invite/rURmwrzUcz in the #dev-blog channel*

**Describe the issue**

- I don't see any broken models. But there is this in the log.
- Single-player
- Large build of mods, possible incompatibility..

**Screenshots**

- 

**log**

> [19:35:10] [Render thread/WARN] [Entity Texture Features/]: Ignoring properties file that caused Exception @ minecraft:optifine/random/entity/zombie/zombie.properties
> java.lang.Exception: Invalid suffix: [0] in [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11].
> java.lang.Exception: Invalid suffix: [0] in [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
> 	at TRANSFORMER/entity_texture_features@6.2/traben.entity_texture_features.features.property_reading.PropertiesRandomProvider.getSuffixes(PropertiesRandomProvider.java:142)
> 	at TRANSFORMER/entity_texture_features@6.2/traben.entity_texture_features.features.property_reading.PropertiesRandomProvider.getAllValidPropertyObjects(PropertiesRandomProvider.java:95)
> 	at TRANSFORMER/entity_texture_features@6.2/traben.entity_texture_features.features.property_reading.PropertiesRandomProvider.of(PropertiesRandomProvider.java:58)
> 	at TRANSFORMER/entity_texture_features@6.2/traben.entity_texture_features.ETFApi$ETFVariantSuffixProvider.getVariantProviderOrNull(ETFApi.java:441)
> 	at TRANSFORMER/entity_texture_features@6.2/traben.entity_texture_features.features.texture_handlers.ETFTextureVariator.of(ETFTextureVariator.java:25)
> 	at TRANSFORMER/entity_texture_features@6.2/traben.entity_texture_features.features.ETFManager.getETFTextureVariant(ETFManager.java:253)
> 	at TRANSFORMER/entity_texture_features@6.2/traben.entity_texture_features.utils.ETFUtils2.getETFVariantNotNullForInjector(ETFUtils2.java:62)
> 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.renderer.RenderType.localvar$coe000$entity_texture_features$etf$mixinAllEntityLayers(RenderType.java:2770)
> 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.renderer.RenderType.m_110443_(RenderType.java)
> 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.renderer.RenderType.m_110458_(RenderType.java:205)
> 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.model.Model.m_103119_(Model.java:18)
> 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.renderer.entity.LivingEntityRenderer.m_7225_(LivingEntityRenderer.java:146)
> 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.renderer.entity.LivingEntityRenderer.m_7392_(LivingEntityRenderer.java:122)
> 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.renderer.entity.MobRenderer.m_7392_(MobRenderer.java:45)
> 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.renderer.entity.MobRenderer.m_7392_(MobRenderer.java:18)
> 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.renderer.entity.EntityRenderDispatcher.m_114384_(EntityRenderDispatcher.java:140)
> 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.renderer.LevelRenderer.m_109517_(LevelRenderer.java:1440)
> 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.renderer.LevelRenderer.invokeRenderEntity(LevelRenderer.java)
> 	at TRANSFORMER/oculus@1.7.0/net.irisshaders.iris.shadows.ShadowRenderer.renderEntities(ShadowRenderer.java:635)
> 	at TRANSFORMER/oculus@1.7.0/net.irisshaders.iris.shadows.ShadowRenderer.renderShadows(ShadowRenderer.java:504)
> 	at TRANSFORMER/oculus@1.7.0/net.irisshaders.iris.pipeline.IrisRenderingPipeline.renderShadows(IrisRenderingPipeline.java:1010)
> 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.renderer.LevelRenderer.handler$bco000$oculus$iris$renderTerrainShadows(LevelRenderer.java:7696)
> 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.renderer.LevelRenderer.m_109599_(LevelRenderer.java:1155)
> 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1126)
> 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:909)
> 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146)
> 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718)
> 	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.main.Main.main(Main.java:218)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
> 	at MC-BOOTSTRAP/fmlloader@1.20.1-47.3.0/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111)
> 	at MC-BOOTSTRAP/fmlloader@1.20.1-47.3.0/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99)
> 	at MC-BOOTSTRAP/fmlloader@1.20.1-47.3.0/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25)
> 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
> 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
> 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
> 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:108)
> 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
> 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
> 	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
> 	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
> 	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:67)
> 	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
> 	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
> 	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

**Your setup: (please complete the following information):**

- Minecraft version: 1,20,1
- ModLoader: Forge
- ETF Version 6.2
- Does the issue persist with only ETF installed?  _(I haven't tried it)_
- Have you checked the FAQ in the Readme, or Discord, to see if it is a known issue?

**Comment by ewanhowell5195** [comment]
i assume you have `skins.0` or `skins.1=0`
`0` is not a valid number here, it starts at `1`

**Comment by Traben-0** [comment]
minecraft:optifine/random/entity/zombie/zombie.properties
has rules with these texture suffixes [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11].

0 is not allowed here.

this used to work and fallback to using the default number `1` last update but has since been given a check that will fail the properties file

**Comment by Traben-0** [comment]
it might also be written as something like `skins.1=0-11`

**Comment by Krimatoria** [comment]
Insanity-Shader-Universal-v1.650.zip

Part of a package of textures that are worth it. The rest, in theory, cannot influence. Although they don't change zombies.
moremcmeta-1.20.1-4.4.7-forge.jar

I have glowing textures, but in theory nothing should affect the zombies visually. Besides the drowned man, his eyes are glowing.

1. Ashen_1.7.zip
2. Ashen_Emissive_Ores.zip
3. All Glowing + 3.0.zip

**Comment by Traben-0** [comment]
there is nothing visually wrong with zombies?

I have also made the log message less intimidating for next update by removing the stack trace for expected errors with custom messages

**Comment by Krimatoria** [comment]
> there is nothing visually wrong with zombies?
> 
> I have also made the log message less intimidating for next update by removing the stack trace for expected errors with custom messages

If I see it, I'll take a screenshot before I see any problems.

**Comment by Krimatoria** [comment]
However, I had absolutely invisible zombies in caves in the last game...Maybe it is?) 😂 And this is not a buff that the witch gives, there weren't even any eyes and particles there either)

**Comment by Traben-0** [comment]
if there is a problem please confirm it doesnt also happen with optifine, as this same limitation should apply there.

It'll be up to the pack dev to fix, if you cant do so yourself
