### ISSUE TITLE
Does this change in 6.2.1 mean, that im no longer able to use etf with Sodium 0.5.11 + Iris 1.7.3?

### ISSUE THREAD

**Issue by girshcatt** [Traben-0/EmissiveMod#299]
"removed old mod compatibility files for older versions of iris, sodium, and immediatelyfast"
sodium 0.6.0 and iris 1.8.0 are in beta lol

**Comment by Traben-0** [comment]
this was compatibility for sodium 0.5.6 ish and iris 1.6....

**Comment by Traben-0** [comment]
as said in the changelog if you use the latest release versions availabl;e for your mc version you are fine
