### ISSUE TITLE
[SUGGESTION] Add more descriptive warning message than "null nbt in ETF"

### ISSUE THREAD

**Issue by zeziba** [Traben-0/EmissiveMod#302]
Playing Chosen's pack Project-Architect-2 and there is log spam from ETF from

```
            if (lastElement == null) {
                ETFUtils2.logWarn("null nbt in ETF");
                return null;
            }
```

The error is as follows `[16:07:05] [Render thread/WARN]: null nbt in ETF.`

[latest.log](https://github.com/user-attachments/files/16790210/latest.log)

This log file contains 9824 instances of this particular line as well for about 1:30hrs of play time or 109 warnings per min. This was already after several texture packs were removed to mitigate the issue and to see what was causing the spam.

Should make it more verbose so that what ever is causing the warning can be quickly found, as of right now it is not easily possible.

**Comment by Traben-0** [comment]
I intend to remove that log message entirely, my testing instance only had completely valid nbt and i had not accounted for the various valid reasons one might declare nbt keys that will fail
