### ISSUE TITLE
[BUG] EMF and ETF now preventing me from loading up the game

### ISSUE THREAD

**Issue by vinnyg0621** [Traben-0/EmissiveMod#309]
*please make sure you are using the latest ETF version before submitting an issue, you might also find a dev build
fixing this issue already on my discord https://discord.com/invite/rURmwrzUcz in the #dev-blog channel*

**Describe the issue**

- What happened? world/game not starting with ETF **and** EMF and newest version of snowy spirit
- What were you doing when it happened?
_with_ the newest version of snowy spirit: game crash on startup, no exit code.
_without_ the newest version of snowy spirit: click on single-player world and just freezes the game entirely, and forever. (never ever loads up the world again)

**Screenshots**

N/A

**Crash log**
[latest.log](https://github.com/user-attachments/files/16988124/latest.log)

**Your setup: (please complete the following information):**

- Minecraft version: 1.20.1
- ModLoader: forge
- EMF version 2.2.5
- ETF Version 6.2.4
- Does the issue persist with only ETF installed?
no
- Have you checked the FAQ in the Readme, or Discord, to see if it is a known issue?
other people have the same issue too

please fix!, I really want to use this mod but I can't anymore!!!

**Comment by Traben-0** [comment]
something about the mod dragon mounts

**Comment by vinnyg0621** [comment]
it's fixed
