### ISSUE TITLE
[BUG] Not all copies of the Illusioner get a custom texture

### ISSUE THREAD

**Issue by magmamir** [Traben-0/EmissiveMod#313]
**Describe the issue**

- Not all, or rather only one illusory copy/duplicate of Illusioner gets a custom random texture.
- This issue doesn't exist in Optifine.

**Screenshots**
With ETF:
![ETF](https://github.com/user-attachments/assets/06ffd176-c317-4b90-93ca-1da2174954b6)
With Optifine:
![Optifine](https://github.com/user-attachments/assets/e9b0ebff-ccf7-4889-92e7-9fc30a7bd9ef)

**Log file**
[latest.log](https://github.com/user-attachments/files/17090679/latest.log) if that might be helpful.

**Resource pack**
Resource pack with this issue. [resources-v0-44.zip](https://github.com/user-attachments/files/17090740/resources-v0-44.zip)
Use `/summon minecraft:illusioner ~ ~ ~ {HandItems:[{},{id:"structure_block",count:1,components:{"minecraft:custom_data":{mmdp:{deformation:{mob:{deformated:{illusioner:1b}}}}}}}]}` to create illusioner with custom texture.

**Your setup:**
- Minecraft version: 1.21
- ModLoader: Quilt Loader
- ETF Version 6.2.5
- Yes
- Yes

**Comment by Traben-0** [comment]
does this occur in 1.21.3?

**Comment by Traben-0** [comment]
hmm it does odd

**Comment by Traben-0** [comment]
fixed for next update
