### ISSUE TITLE
[BUG] "ETF Config button disappears or moves when the window is resized"

### ISSUE THREAD

**Issue by SoulxluoS** [Traben-0/EmissiveMod#325]
**Describe the issue**
- ETF Config button disappears or moves when the window is resized.

**Video**

https://github.com/user-attachments/assets/bc8c89ab-4a19-43e7-9ef4-132e44093286

**Setup:**
- Minecraft version: [1.21.1-1.21.3]
- ModLoader: [Fabric]
- ETF Version [6.2.7]
- Does the issue persist with only ETF installed? - [ETF + ModMenu + FabricAPI]

**Comment by Traben-0** [comment]
fixed next update
