### ISSUE TITLE
[BUG] [PARITY] ETF incorrectly loads textures from optifine\random\entity

### ISSUE THREAD

**Issue by ZenithRogue** [Traben-0/EmissiveMod#327]
**Describe the issue**

When using random entities, placing `<entity>.png` in the `minecraft\optifine\random\entity\` folder, ETF will load this image, replacing the default `<entity>.png` from `minecraft\textures\entity\`. This is inconsistent with OptiFine behavior. OptiFine only loads the numerically identified textures (ie `<entity>2.png`), it never replaces the default image.

**Screenshots**

![image](https://github.com/user-attachments/assets/166f1168-4619-4f66-ac6a-ec4b7af09750)

**Crash log**

* N/A

**Comment by Traben-0** [comment]
fixed in 6.2.8
