### ISSUE TITLE
Updating and improving the Ukrainian translation

### ISSUE THREAD

**Issue by StarmanMine142** [Traben-0/EmissiveMod#331]
Could you add an improved and updated Ukrainian translation to the mod?

[uk_ua.json](https://github.com/user-attachments/files/18014856/uk_ua.json)

**Comment by StarmanMine142** [comment]
@Traben-0 ?

**Comment by Traben-0** [comment]
I will for the next update to the 3 mods

**Comment by StarmanMine142** [comment]
Pull request: https://github.com/Traben-0/Entity_Texture_Features/pull/333
