### ISSUE TITLE
[BUG] "Animated textures dont work properly"

### ISSUE THREAD

**Issue by samuelhenrique4** [Traben-0/EmissiveMod#337]
Animated textures simply doen't work properly

[Chests Reforged](https://modrinth.com/resourcepack/chests-reforged)
[Village & Pillage Reforged](https://modrinth.com/resourcepack/village-pillage-reforged)
^In those links are the resources not working^.

More specifically the iron golem:
![2024-12-14_17 19 35](https://github.com/user-attachments/assets/1b09995a-5c4f-4794-a581-9d704719d21a)

And the animated chests:
![2024-12-14_17 21 36](https://github.com/user-attachments/assets/e0dd0b2a-e7dc-4227-b410-8a0cb0d1bbef)

Besides that everything is right and working well. Look at her! She's so happy! :
![2024-12-14_17 21 42](https://github.com/user-attachments/assets/2861013a-19ac-48e8-955b-a3c90ccba25c)

Sorry if I am only being dumb as fuck and just dont know how to configure you mod, thanks in advance!
[debug.log](https://github.com/user-attachments/files/18137614/debug.log)
[debug-1.log.gz](https://github.com/user-attachments/files/18137616/debug-1.log.gz)
[2024-12-14-7.log.gz](https://github.com/user-attachments/files/18137617/2024-12-14-7.log.gz)
[latest.log](https://github.com/user-attachments/files/18137618/latest.log)
-Minecraft 1.20.4
-NeoForge 21.4.22-beta
-ETF 6.2.9
-EMF 2.3.1

**Comment by Traben-0** [comment]
etf and emf do not handle animated textures as the animatica and moremcmeta mods already do so, you will need to see if they have neoforge ports
