### ISSUE TITLE
[SUGGESTION] Config to enable/disable either random and emissive textures

### ISSUE THREAD

**Issue by johngabriel-mercado** [Traben-0/EmissiveMod#4]
People might want just random textures but not emissive. So in the future, you can add a way to disable either feature?

Also right now, I would prefer disabling emissive as right now, it's a bit broken with the resource pack that I am using (I know there's a problem but I haven't been able to determine what it is yet) in favor of using Puzzle's implementation at least while you iron out the kinks.

**Comment by Traben-0** [comment]
Its just been updated and should now handle emissives the same as the puzzle mod, if its the bug where the mobs are all white that has been fixed
going to add a config soon to allow disabling of features

if it wasn't fixed can you send a link to the resourcepack and i'll look into it
