### ISSUE TITLE
Mod version shows 1.18.1 (instead of 2.0+1.18 or something)

### ISSUE THREAD

**Issue by MeeniMc** [Traben-0/EmissiveMod#5]
In MultiMC, the 'Version' column shows 1.18.1 instead of the version of the mod itself.

Same thing in ModMenu in-game. 

Not a big deal, it's probably because the wrong field has been setup in fabric.properties.

**Comment by Traben-0** [comment]
yep exactly what it was, was putting that off until I actually put in the modmenu integration, fixed now
