### ISSUE TITLE
I'd like to turn Puzzle and Iris notifications off

### ISSUE THREAD

**Issue by shizotoaster** [Traben-0/EmissiveMod#8]
![изображение](https://user-images.githubusercontent.com/51480483/151663481-f508e542-e546-441c-aaec-24a6ec3ffa68.png)
These messages appear in console and chat every time I reload my resource packs. I would like to have an ability of turning them off

**Comment by SinsOfVirtue** [comment]
To add onto this, if change your resource packs, you'll get spammed with the message in chat several times. I have my Puzzle and Iris settings as the mod requested, it'd be nice if that would keep the messages from popping up if a toggle in Mod Menu can't be added.

**Comment by Traben-0** [comment]
I just turned off the chat messages in [V2.1.0], I was finishing optifine properties feature parity before I got too settings & configs, now that thats done I will be adding cloth config & modmenu support in a few days with a setting to dasable these messages/only play them once if not tonight.
