### ISSUE TITLE
[1.19] [Quilt] Skeletons are invisible

### ISSUE THREAD

**Issue by stantios** [Traben-0/EmissiveMod#87]
I'm not sure on how to describe it but I used this pack called 'Better Skeletons' and when I when in game the skeletons are invisible like this. I've tried the latest beta of ETF but it still didn't fix the issue, here are my logs if needed: https://mclo.gs/Y3UdTu5

![](https://cdn.discordapp.com/attachments/826497302105554984/999617031697600583/20220721_094737.jpg)

**Comment by Traben-0** [comment]
this looks like a CEM issue that pack uses alot of custom models, do you have CEM installed and configured right?
