### ISSUE TITLE
Crash at Serverstart

### ISSUE THREAD

**Issue by TheButterbrotMan** [Traben-0/EmissiveMod#9]
https://bytebin.lucko.me/goWtxa9Tu9

**Comment by Traben-0** [comment]
it looks like you tried to run this on a server doesn't look like the singleplayer internal server either, this is a client side only mod that would only work on the client

**Comment by TheButterbrotMan** [comment]
Please add an clienttag to it, so server doesnt attempt to load it.

**Comment by Traben-0** [comment]
Fixed as of 2.1.2 thanks for pointing that out didn't know about that tag
